### ISSUE TITLE
Collapse server and client

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/CyberBird#14]
Сейчас сервер это node.js приложение, а веб клиент/управление это nginx раздаваемый сайт

Разноситься в два репозитория эти части будут вряд ли, значит и клиент и сервер будут обновляться одновременно всегда, и нет большого смысла делать отдельные
* Сервер
* Клиент
* Прокси для объединения

Необходимо собирать сервер и веб клиент так, чтобы сервер раздавал сборку клиента, и был всего один сервис вместо бесполезных трех. Ибо сейчас это доп нагрузка на поддержку, devops, дополнительные контейнеры, и прочее.

**Comment by IvLaptev** [comment]
По идее надо только допилить раздачу статики нодой, да? Речь же не идёт о том, что я должен собрать физически все 3 папки в одну?

**Comment by CAPCHIK** [comment]
Да, допилить раздачу нодой и например прямо тут мне объяснить, как надо будет собирать проект, чтобы я переписал аккуратно CI

**Comment by CAPCHIK** [comment]
Ну или можешь сам заняться, ничего сверх естественного там ет
